### PR TITLE
Follow some of the IDE's recommendations

### PR DESCRIPTION
**Pull request by jtraglia**
## PR Description

With one exception, this all pertains to Java code.

* Remove duplicate entry from `.gitignore` file.
* Use a try-with-resource statement for getting the interlock session key.
* Remove some unnecessary semicolons.
* Remove an unnecessary `toString()` call.
* Replace a lambda with a method reference.
* Replace some statement lambdas with expression lambdas.
* Replace `count() > 0` with `findAny().isPresent()`.
  * Source for why it's better: https://stackoverflow.com/a/39721919
* Replace `Collection.addAll()` with faster instantiation.
* Surround link in html hyperlink tag.
* Remove unnecessary `throws` from two funcs.

Thanks to IntelliJ's IDEA for pointing these things out.

## Documentation

- [x] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [x] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Review by siladu — APPROVED** [review]
Thanks for the contributions! This is great.

**Comment by siladu** [comment]
@jtraglia looks like there's an issue triggering the builds, can you check if you're following your fork of web3signer on CircleCI and unfollow it if so, see https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-#:~:text=If%20you%27re%20following%20the%20fork%20instead%20of%20the%20upstream%20repo

**Comment by jtraglia** [comment]
Hey @siladu no problem, happy to contribute. I don't believe I am following the fork, but I'm not totally sure.

When I log in and filter to this project, my fork isn't even setup:

Screen Shot 2022-09-04 at 5 09 31 PM

Regardless, you may want to configure CircleCI to run on forked projects.

> By default, CircleCI does not build PRs from forked repositories. To change this setting, go to the Project Settings>Advanced of your project and set the Build forked pull requests option to On.

Source: https://circleci.com/docs/oss#build-pull-requests-from-forked-repositories

**Comment by siladu** [comment]
@jtraglia you'll need to merge master into your PR branches I'm afraid as I've just had to fix a newly discovered CVE vulnerability that will block the PR going through.

Thanks for checking in circleci. I think it might be something to do with authorisation actually. I'll look it into, but I should be able manually trigger your builds for now, once you've got the latest master :)

**Comment by jtraglia** [comment]
Okay sounds good. I'll do that! Also, I'm used to there being a "this branch is out-of-date with the base branch" at the bottom of PRs that are out of sync, but I don't see that here. Is that a project setting?

For example:

image

**Comment by siladu** [comment]
I expect it's because there's no conflict, so your PR would merge into master nicely, even with changes on master.
However, in this case the lib update is necessary for one of the PR checks

**Comment by jtraglia** [comment]
Sorry, I think I may have merged these incorrectly for this PR & #634. Are these okay?

**Comment by siladu** [comment]
Hmmm yeh, they've ended up with the wrong commit hash. It's probably not a problem since it'll all get squashed into one commit in the end, but can't hurt to try to sort it out in the PR if you don't mind, just in case. You should be able to force push if you need to.

**Comment by jtraglia** [comment]
Alright, fixed for both! Sorry about that.

**Comment by siladu** [comment]
No worries, thanks again for these contributions :)

**Pull request merged**
