### PR TITLE
Split up OpenAPI spec into multiple files to prepare for new key manager api integration

### PR DESCRIPTION
**Pull request by joaquim-verges**
first preliminary step to start integrating the key manager API as discussed in #439 

This PR doesn't introduce any changes, just organizes the OpenAPI yaml file to make it easier and cleaner to add the new key manager endpoints, which will be in the follow up PR.

### CODE REVIEW

**Review by dapplion — APPROVED** [review]
:pray:

**Comment by jframe** [comment]
Looks good, just want to check that the open api publishing still works.

**Comment by joaquim-verges** [comment]
@jframe how do we check that the publishing works?

**Comment by usmansaleem** [comment]
@joaquim-verges we have a gh-pages branch which ends up rendering OpenAPI doc at https://consensys.github.io/web3signer/ for each master/release commit. The circlecli (CI) executes `npm ci` on `https://github.com/ConsenSys/web3signer/tree/master/.openapidoc` which is a nodejs project which replaces version in the yaml and pushes them to gh-pages branch. 

We need to perform a quick sanity test whether the separated yaml files also gets published or not. Its been sometime since we have worked on this script (its kinda like "once it worked, leave it alone script"). Might need a bit of hack to figure out which files will be pushed without actually pushing remotely (while working on it in local dev mode).

**Comment by jframe** [comment]
@joaquim-verges Was just testing the swagger-ui endpoint it's not able to display the openapi spec anymore in web3signer.
Screenshot: . 

Most likely because the referenced yaml files cannot be served. In the Runner we register a single file that we are expecting to contain the openapi doc https://github.com/ConsenSys/web3signer/blob/master/core/src/main/java/tech/pegasys/web3signer/core/Runner.java#L232

**Comment by joaquim-verges** [comment]
@usmansaleem @jframe  thanks for checking/testing! That's what I was worried about, seems like not all tools support external `$ref` out of the box.

There is an option which would be to compile the split API spec into a single file, using something like https://github.com/mohsen1/multi-file-swagger-example

It does introduce an extra build step though, not sure how you guys feel about that.

The whole reason for doing this is purely for code organization (it does make the main API spec nice and tidy), but if it brings annoying problems it might not be worth it.

Let me know what you want to do here, either:

a. Just add the new endpoints to the main API spec (simplest solution, but will be a fairly large API spec with the 3 extra key manager endpoints + schemas)
b. Explore the single file compilation route / fix the tools in order to keep a clean API spec file

**Comment by usmansaleem** [comment]
@joaquim-verges I am going to change the nodejs script that publishes to gh-pages .. so that it uses version in a directory instead of in filename. This will allow relative paths to work correctly. I'll also work on fixing the swagger-ui stuff. Your PR would need to wait till that work goes in. Should be in couple of days max.

**Comment by joaquim-verges** [comment]
@usmansaleem that would be awesome, thank you! No rush, it doesn't block me. I can keep working on the key manager APIs in the meantime.

**Comment by jframe** [comment]
@joaquim-verges It is seems tools don't seem to like multiple yaml files that much. Glad Vertx worked with the multiple files though.

We chatted a bit about an approach so I think we should be able to get something working though.

**Comment by dapplion** [comment]
This repo hosts an OpenAPI specification in multiple files that are bundled and deployed successfully https://github.com/ethereum/beacon-APIs/blob/master/.github/workflows/release.yaml

**Comment by usmansaleem** [comment]
https://github.com/ConsenSys/web3signer/pull/447 should address this PR (will close once merged).

**Comment by usmansaleem** [comment]
Implemented by #447

**Pull request closed without merging**
