### PR TITLE
Fix naming issues in test code

### PR DESCRIPTION
**Pull request by jtraglia**
## PR Description

This PR fixes naming issues in the testing source trees.

Associated with #687 which fixes naming issues in the main source tree.

## Documentation

- [x] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [x] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Comment by jtraglia** [comment]
Hmm the build failed the dependency vulnerability scan.

**Review by jframe — APPROVED** [review]
LGTM

**Comment by jframe** [comment]
> Hmm the build failed the dependency vulnerability scan.

It's caused by a false positive, unfortunately. We have added a suppression for this that has been merged into the master branch until that has been fixed.

**Review by usmansaleem — APPROVED** [review]
LGTM

**Pull request merged**
