### PR TITLE
Rename the eth cmd line option --enable-key-manager-api to --key-manager-api-enabled

### PR DESCRIPTION
**Pull request by jframe**
Rename the eth cmd line option --enable-key-manager-api to --key-manager-api-enabled to make it consistent with the other Web3Signer command options that have -enabled suffix.

### CODE REVIEW

**Review by siladu — APPROVED** [review]
LGTM

**Comment by joaquim-verges** [comment]
Thank you @jframe !

**Comment by prestonvanloon** [comment]
Please alias the old flag name. I am running from HEAD and was broken with this error. 

```
Error parsing parameters: Unknown option: '--enable-key-manager-api=true'
```

**Comment by jframe** [comment]
Looks like the old flag went out in a release so adding an alias for it see #518.

**Pull request merged**
